name: "Publish TranslationTools Client (NuGet)"

on:
   workflow_dispatch:
   push:
      branches:
      - master
      paths:
      - "nuget/mvdmio.TranslationTools.Client/**"
      - "nuget/mvdmio.TranslationTools.Client.SourceGenerator/**"
      - "test/TranslationTools/mvdmio.TranslationTools.Client.Tests.Unit/**"

jobs:
   Publish_TranslationTools_Client:
      runs-on: ubuntu-22.04
      steps:
      -  uses: actions/checkout@v4

      -  name: Setup NuGet.exe for use with actions
         uses: nuget/setup-nuget@v2
         with:
            nuget-api-key: ${{secrets.NUGET_API_KEY}}
            nuget-version: 'latest'

      -  name: Setup .NET
         uses: actions/setup-dotnet@v4
         with:
            dotnet-version: 10.0.x

      -  name: Restore package and tests
         run: |
            dotnet restore nuget/mvdmio.TranslationTools.Client/mvdmio.TranslationTools.Client.csproj
            dotnet restore nuget/mvdmio.TranslationTools.Client.SourceGenerator/mvdmio.TranslationTools.Client.SourceGenerator.csproj
            dotnet restore test/TranslationTools/mvdmio.TranslationTools.Client.Tests.Unit/mvdmio.TranslationTools.Client.Tests.Unit.csproj

      -  name: Build package
         run: dotnet build nuget/mvdmio.TranslationTools.Client/mvdmio.TranslationTools.Client.csproj --configuration Release --no-restore

      -  name: Test client package
         run: dotnet test test/TranslationTools/mvdmio.TranslationTools.Client.Tests.Unit/mvdmio.TranslationTools.Client.Tests.Unit.csproj --configuration Release --no-restore --verbosity normal

      -  name: Pack and publish package
         run: |
            dotnet pack nuget/mvdmio.TranslationTools.Client/mvdmio.TranslationTools.Client.csproj --configuration Release --no-build -o ./artifacts
            nuget push ./artifacts/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -NonInteractive -SkipDuplicate -Verbosity normal
